/* REFERENCE SCRIPT: DS domain - gold standard for GEPA scoring */
/* Generated by generate_synthetic.py for study STUDY001 */

/*****************************************************************************
 * Program    : ds.sas
 * Domain     : DS - Disposition
 * Class      : Special Purpose
 * Source     : RAW_DS (disposition CRF data)
 * SDTM Ref   : SDTM IG v3.4 Section 5.4
 *****************************************************************************/

data sdtm.ds;
    length STUDYID $20 DOMAIN $2 USUBJID $40
           DSTERM $200 DSDECOD $50 DSCAT $40 DSSCAT $40 EPOCH $40
           DSDTC DSSTDTC $10;
    length DSSEQ DSDY DSSTDY 8;

    set raw.raw_ds;

    STUDYID  = "STUDY001";
    DOMAIN   = "DS";
    USUBJID  = catx(".", STUDYID, SITEID, SUBJID);
    DSSEQ    = SEQ;
    DSTERM   = DS_TERM;
    DSDECOD  = DS_DECOD;
    DSCAT    = DS_CAT;
    EPOCH    = DS_EPOCH;
    DSSTDTC  = DS_DATE;
    if DSSTDTC ne "" then
        DSSTDY = input(DSSTDTC, yymmdd10.) - input(RFSTDTC, yymmdd10.) + 1;

    label
        STUDYID  = "Study Identifier"
        DOMAIN   = "Domain Abbreviation"
        USUBJID  = "Unique Subject Identifier"
        DSSEQ    = "Sequence Number"
        DSTERM   = "Reported Term for the Disposition Event"
        DSDECOD  = "Standardized Disposition Term"
        DSCAT    = "Category for Disposition Event"
        EPOCH    = "Epoch"
        DSSTDTC  = "Start Date/Time of Disposition Event"
        DSSTDY   = "Study Day of Start of Disposition Event";

    keep STUDYID DOMAIN USUBJID DSSEQ DSTERM DSDECOD DSCAT DSSCAT EPOCH
         DSDTC DSDY DSSTDTC DSSTDY;
run;

proc sort data=sdtm.ds; by STUDYID USUBJID DSSEQ; run;
