/* REFERENCE SCRIPT: EX domain - gold standard for GEPA scoring */
/* Generated by generate_synthetic.py for study STUDY001 */

/*****************************************************************************
 * Program    : ex.sas
 * Domain     : EX - Exposure
 * Class      : Interventions
 * Source     : RAW_EX (study drug dispensing / administration data)
 * SDTM Ref   : SDTM IG v3.4 Section 6.5
 *****************************************************************************/

data sdtm.ex;
    length STUDYID $20 DOMAIN $2 USUBJID $40
           EXTRT $200 EXDOSU $20 EXDOSFRM $40 EXDOSFRQ $10 EXROUTE $20
           EXSTDTC EXENDTC $10 VISIT $40;
    length EXSEQ EXDOSE EXDOSTOT EXSTDY EXENDY VISITNUM 8;

    set raw.raw_ex;

    STUDYID  = "STUDY001";
    DOMAIN   = "EX";
    USUBJID  = catx(".", STUDYID, SITEID, SUBJID);
    EXSEQ    = SEQ;
    EXTRT    = TRT_NAME;
    EXDOSE   = DOSE;
    EXDOSU   = DOSE_UNITS;
    EXDOSFRM = DOSE_FORM;
    EXDOSFRQ = DOSE_FREQ;
    EXROUTE  = ROUTE;
    EXSTDTC  = ADMIN_DATE;
    EXENDTC  = END_DATE;
    VISITNUM = VISIT_NUM;
    VISIT    = VISIT_NAME;

    if EXSTDTC ne "" then
        EXSTDY = input(EXSTDTC, yymmdd10.) - input(RFSTDTC, yymmdd10.) + 1;
    if EXENDTC ne "" then
        EXENDY = input(EXENDTC, yymmdd10.) - input(RFSTDTC, yymmdd10.) + 1;

    label
        STUDYID  = "Study Identifier"
        DOMAIN   = "Domain Abbreviation"
        USUBJID  = "Unique Subject Identifier"
        EXSEQ    = "Sequence Number"
        EXTRT    = "Name of Actual Treatment"
        EXDOSE   = "Dose per Administration"
        EXDOSU   = "Dose Units"
        EXDOSFRM = "Dose Form"
        EXDOSFRQ = "Dosing Frequency per Interval"
        EXROUTE  = "Route of Administration"
        EXSTDTC  = "Start Date/Time of Treatment"
        EXENDTC  = "End Date/Time of Treatment"
        EXSTDY   = "Study Day of Start of Treatment";

    keep STUDYID DOMAIN USUBJID EXSEQ EXTRT EXDOSE EXDOSU EXDOSFRM EXDOSFRQ
         EXROUTE EXSTDTC EXENDTC EXSTDY EXENDY VISITNUM VISIT;
run;

proc sort data=sdtm.ex; by STUDYID USUBJID EXSTDTC EXSEQ; run;
